v0:
    env: continuous-grid
    run: PPO
    local_dir: /s/ls4/users/grartem/RL_robots/RL_robotSim/results/FollowerContinuous/PPO/tests
    checkpoint_freq: 10
    stop:
        training_iteration: 500
    config:
        # Works for both torch and tf.
        env_config:
            name: Test-Cont-Env-Auto-v0
            framestack: 20
        log_level: WARNING
        framework: torch
        num_gpus: 1
        timesteps_per_iteration: 20000
        # === Model ===
        num_workers: 2
        model:
            fcnet_hiddens: [256, 256, 256]
            fcnet_activation: relu
        gamma: 0.99
        lr: .0001
        train_batch_size: 20000
        sgd_minibatch_size: 1024
        num_sgd_iter: 5