v0:
    env: continuous-grid
    run: A3C
    local_dir: /s/ls4/users/grartem/RL_robots/RL_robotSim/results/FollowerContinuous/noObst_constSpeed/A3C/
    checkpoint_freq: 10
    stop:
        training_iteration: 2000
    config:
        num_gpus: 1
        timesteps_per_iteration: 5000
        num_workers: 4
        log_level: WARNING
        framework: torch
        # === Env config ===
        env_config:
            name: Test-Cont-Env-Auto-v0
            base_env_config:
                warm_start: 0
                max_steps: 5000
                frames_per_step: 5
                add_obstacles: False
                framerate: 5000
                constant_follower_speed: True
                early_stopping:
                    max_distance_coef: 1.3
                    low_reward: -200
                follower_sensors:
                    LeaderCorridor_lasers:
                        sensor_name: LeaderCorridor_lasers
                    LeaderPositionsTracker:
                        eat_close_points: True
                        generate_corridor: True
                        saving_period: 8
                        sensor_name: LeaderPositionsTracker
                    LeaderTrackDetector_radar:
                        detectable_positions: near
                        position_sequence_length: 100
                        radar_sectors_number: 7
                        sensor_name: LeaderTrackDetector_radar
                    LeaderTrackDetector_vector:
                        position_sequence_length: 10
                        sensor_name: LeaderTrackDetector_vector
            wrappers: ['ContinuousObserveModifier_v0']
        # === Model ===
        model:
            fcnet_hiddens: [8, 8]
            fcnet_activation: relu
            use_lstm: True
            lstm_use_prev_action: True
            lstm_use_prev_reward: True
            max_seq_len: 100
            lstm_cell_size: 8
        # === Learning settings ===
        gamma: 0.99
        lr: .00001
        batch_mode: complete_episodes
        train_batch_size: 5000
        # === Exploration Settings ===
        explore: True
        exploration_config:
            type: GaussianNoise
            random_timesteps: 10
            stddev: 0.1

    